### ISSUE TITLE
GitHub signup: "Internal server error"

### ISSUE THREAD

**Issue by jorisbontje** [nate-strauser/wework#24]
from the logs:
```
Exception while invoking method 'login' undefined
```

This happens both locally and when using http://www.weworkmeteor.com/sign-up

**Comment by nate-strauser** [comment]
i just deleted my github based user, then signed up successfully with it

i do see this in the logs though
`Exception while invoking method 'login' { stack: undefined, source: 'method' }`

do you get anything more useful for debugging when the error happens locally?

**Comment by jorisbontje** [comment]
After changing `overrideLoginErrors` to `false` in `lib/accounts.js`, I get the following exception instead:
```
Exception while invoking method 'login' Error: Full Name is required
    at getErrorObject (packages/aldeed:collection2/collection2.js:363:1)
    at [object Object].doValidate (packages/aldeed:collection2/collection2.js:346:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:147:1)
    at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1042:1)
    at Object.Accounts.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1189:1)
    at [object Object].Package (packages/accounts-oauth/oauth_server.js:45:1)
    at packages/accounts-base/accounts_server.js:383:1
    at tryLoginMethod (packages/accounts-base/accounts_server.js:186:1)
    at runLoginHandlers (packages/accounts-base/accounts_server.js:380:1)
    at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:434:1)
Sanitized and reported to the client as: Full Name is required [400]
```

**Comment by nate-strauser** [comment]
ah ok - i can make that profile field optional

**Comment by nate-strauser** [comment]
try again, let me know if it is still an issue -- i must have more fields filled out on my github profile or something, guessing that's why it works for me

**Comment by jorisbontje** [comment]
yep, that works now. (even though the `getCurrentUserDisplayName` in topnav will be left empty if you dont have a full name setup on github).

thanks!
